title: My Title
author: kaitoii11
email: kaitoii1111@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  description

# social links
twitter_username: your-twitter-handle
github_username:  kaitoii11

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
